language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  apt:
    packages:
      - openjdk-8-source

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
